# Generated by Django 5.2.3 on 2025-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scraper_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('records', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
